### ISSUE TITLE
Got this error when trying to run.

### ISSUE THREAD

**Issue by MvONEr** [ExtropyIO/defi-bot#9]
I’m very new to this coding thing, but I really wanna learn and thought this project could help me learn, but when I tried to run it it threw this error: syntax error: unexpected identifier. 
I can’t understand anything can somebody please help me how to set this bot up.
When I opened it up I just made a .env file and filled it nothing more. 
Do I have to do anything more or what. Im completely lost at this point.

**Comment by Hackdwerg** [comment]
If you are new to this, you should really begin with the basics. You can’t just deep dive into this for the sake of making money. For starters, you gotta really start from scratch. Learning how to code to make money should not be your first reason.

**Comment by restorepro** [comment]
MvONEr, what file is throwing the error and what line is the error on in that file? Maybe paste in the error code or attach a screenshot...

**Comment by JK5768** [comment]
I am also getting the same error. Here are the details:
SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:60:12)
    at internal/main/run_main_module.js:17:47
